### ISSUE TITLE
Only pulled one page

### ISSUE THREAD

**Issue by tripleo1** [peterk/warcworker#12]
*  How do I pull an entire website with this
*  How do I see what it is doing internally?

**Comment by peterk** [comment]
1. Warcworker is for single page archiving only right now. There is no crawler or indexer. 
2. If you want to monitor logs run `docker-compose logs --tail=100 -t -f`

**Comment by tripleo1** [comment]
Thats an awful lot of work for just one page.

**Comment by peterk** [comment]
:-) Well, I use it for mass archiving of URLs collected by a custom crawler from js heavy websites. It does its job. For regular archiving see [Heritrix](https://github.com/internetarchive/heritrix3).

**Comment by peterk** [comment]
You could check out the archiving component of warcworker - [Squidwarc](https://github.com/N0taN3rd/Squidwarc) - it has  settings that may help you in archiving more links of a website (see Page + Same Domain Links setting).

**Comment by tripleo1** [comment]
Thanks. Was just looking at that.

**Comment by peterk** [comment]
If I remember correctly it only captures the current page and all the links from that page so it will not capture an entire website. If the website you are archiving is not dependant on running scripts in the archiving tool you could check out [HTTRack](https://www.httrack.com/) as well.

**Comment by peterk** [comment]
Closing
