### ISSUE TITLE
Consider using text other than "Archive it!" in the interface

### ISSUE THREAD

**Issue by machawk1** [peterk/warcworker#9]
Internet Archive runs a service called "[Archive-It](https://archive-it.org/)" that many that do personal archiving use.

The screenshot (and interface elements when testing) made me initially question what this tool has to do with Archive-It. As a suggestion: maybe put the name of the tool (warcworker) in the header box and something more representative (e.g., Archive URLs) in the button text. This would prevent any confusion and still be descriptive of what the tool accomplishes.

**Comment by peterk** [comment]
Thank you for your feedback. You are right. This was confusing. Added "Warcworker" to the header and changed the button.

**Comment by edsu** [comment]
I honestly thought it was ironically done on purpose :-)
